% generated by hhProblemGen; format=tff; type_enc=mono_native_fool; lam_trans=lifting; mono_iters=3; mono_instances=100
% Declarations (83)
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Enum__2Enum, type,
    ty_2Enum_2Enum : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Ebool, type,
    ty_2Emin_2Ebool : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Ebool__2Cnum__2Enum__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Ebool_2Cnum_2Enum_29_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Ebool__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Ebool_2Cnum_2Enum_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Ebool__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Ebool_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29 : $tType).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Enum_2Enum * ty_2Enum_2Enum) > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ebool__2ECOND__2Enum__2Enum, type,
    c_2Ebool_2ECOND_2Enum_2Enum : (ty_2Emin_2Ebool * ty_2Enum_2Enum * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 * ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29) > ty_2Emin_2Ebool).
tff(sy_2E__24not, type,
    _24not : ty_2Emin_2Ebool > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ebool__2ECOND__2Emin__2Ebool, type,
    c_2Ebool_2ECOND_2Emin_2Ebool : (ty_2Emin_2Ebool * ty_2Emin_2Ebool * ty_2Emin_2Ebool) > ty_2Emin_2Ebool).
tff(sy_2E__24true, type,
    _24true : ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29) > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : (ty_2Emin_2Ebool * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 * ty_2Emin_2Ebool) > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : (ty_2Emin_2Ebool * ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 * ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29 * ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29) > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28min__2Ebool__2Cnum__2Enum__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29 : (ty_2Emin_2Ebool * ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29 * ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29 * ty_2Emin_2Ebool) > ty_2Enum_2Enum).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29) > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28num__2Enum__2Cmin__2Ebool__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 : (ty_2Emin_2Ebool * ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 * ty_2Enum_2Enum) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29) > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : (ty_2Emin_2Ebool * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Emin_2Ebool * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29) > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : (ty_2Emin_2Ebool * ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29 * ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29) > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29 : (ty_2Emin_2Ebool * ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29 * ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29) > ty_2Enum_2Enum).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29) > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 : (ty_2Emin_2Ebool * ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29) > ty_2Emin_2Ebool).
tff(sy_2E__24false, type,
    _24false : ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29 * ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29) > ty_2Emin_2Ebool).
tff(sy_2Eapp, type,
    app_2E : ($i * $i) > $i).
% Helpers (31)
tff(help_2Eif__True, axiom,
    ((![HX : ty_2Emin_2Ebool]: (![HY : ty_2Emin_2Ebool]: (app_2E(c_2Ebool_2ECOND_2Emin_2Ebool(_24true,HX),HY) <=> HX))))).
tff(help_2Eif__True_2E2, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: app_2E(_24equal(app_2E(c_2Ebool_2ECOND_2Enum_2Enum(_24true,HX),HY)),HX))))).
tff(help_2Eif__True_2E3, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: app_2E(_24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(_24true,HX,HY)),HX))))).
tff(help_2Eif__True_2E4, axiom,
    ((![HX : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (![HY : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: app_2E(_24equal(c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(_24true,HX,HY)),HX))))).
tff(help_2Eif__True_2E5, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: (![HY : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29(_24true,HX,HY),HX))))).
tff(help_2Eif__True_2E6, axiom,
    ((![HX : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29(_24true,HX,HY),HX))))).
tff(help_2Eif__True_2E7, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![HY : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29(_24true,HX,HY),HX))))).
tff(help_2Eif__True_2E8, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29(_24true,HX,HY),HX))))).
tff(help_2Eif__True_2E9, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: (![HY : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29(_24true,HX,HY),HX))))).
tff(help_2Eif__True_2E10, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29(_24true,HX,HY),HX))))).
tff(help_2Eif__False, axiom,
    ((![HX : ty_2Emin_2Ebool]: (![HY : ty_2Emin_2Ebool]: (app_2E(c_2Ebool_2ECOND_2Emin_2Ebool(_24false,HX),HY) <=> HY))))).
tff(help_2Eif__False_2E2, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: app_2E(_24equal(app_2E(c_2Ebool_2ECOND_2Enum_2Enum(_24false,HX),HY)),HY))))).
tff(help_2Eif__False_2E3, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: app_2E(_24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(_24false,HX,HY)),HY))))).
tff(help_2Eif__False_2E4, axiom,
    ((![HX : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (![HY : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: app_2E(_24equal(c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(_24false,HX,HY)),HY))))).
tff(help_2Eif__False_2E5, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: (![HY : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29(_24false,HX,HY),HY))))).
tff(help_2Eif__False_2E6, axiom,
    ((![HX : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29(_24false,HX,HY),HY))))).
tff(help_2Eif__False_2E7, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![HY : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29(_24false,HX,HY),HY))))).
tff(help_2Eif__False_2E8, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29(_24false,HX,HY),HY))))).
tff(help_2Eif__False_2E9, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: (![HY : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29(_24false,HX,HY),HY))))).
tff(help_2Eif__False_2E10, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29]: _24equal(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29(_24false,HX,HY),HY))))).
tff(help_2Ebool__cases, axiom,
    ((![HB : ty_2Emin_2Ebool]: ((HB <=> _24true) | (HB <=> _24false))))).
tff(help_2Eeq__ext, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: ((![V_x : ty_2Emin_2Ebool]: (app_2E(V_f,V_x) <=> app_2E(V_g,V_x))) => app_2E(_24equal(V_f),V_g)))))).
tff(help_2Eeq__ext_2E2, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: ((![V_x : ty_2Emin_2Ebool]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E3, axiom,
    ((![V_f : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: (![V_g : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: ((![V_x : ty_2Enum_2Enum]: (app_2E(V_f,V_x) <=> app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E4, axiom,
    ((![V_f : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: ((![V_x : ty_2Enum_2Enum]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => app_2E(_24equal(V_f),V_g)))))).
tff(help_2Eeq__ext_2E5, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: ((![V_x : ty_2Emin_2Ebool]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E6, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29]: (![V_g : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29]: ((![V_x : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (app_2E(V_f,V_x) <=> app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E7, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: ((![V_x : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E8, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29]: (![V_g : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29]: ((![V_x : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (app_2E(V_f,V_x) <=> app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E9, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29]: ((![V_x : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E10, axiom,
    ((![V_f : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![V_g : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: ((![V_x : ty_2Enum_2Enum]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
% Facts (2)
tff(lam_2E0, axiom,
    ((![X : ty_2Enum_2Enum]: _24equal(app_2E(V_lam_2E0,X),X)))).
tff(lam_2E1, axiom,
    ((![X : ty_2Enum_2Enum]: _24equal(app_2E(V_lam_2E1,X),X)))).
% Conjecture (1)
tff(conjecture, conjecture,
    ((![P : ty_2Emin_2Ebool]: (![X : ty_2Enum_2Enum]: (![Y : ty_2Enum_2Enum]: (![V_use__bool : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (_24equal(c_2Ebool_2ECOND_2Enum_2Enum(P,X,Y),X) & (_24equal(V_lam_2E0,V_lam_2E1) & (app_2E(V_use__bool,app_2E(_24not,P)) & _24equal(X,X)))))))))).
