% generated by hhProblemGen; format=tff; type_enc=poly_native; lam_trans=lifting; mono_iters=3; mono_instances=100
% Declarations (20)
tff(ty_2Ety__2Emin__2Efun, type,
    ty_2Emin_2Efun : ($tType * $tType) > $tType).
tff(ty_2Ety__2Emin__2Ebool, type,
    ty_2Emin_2Ebool : $tType).
tff(ty_2Ety__2Enum__2Enum, type,
    ty_2Enum_2Enum : $tType).
tff(ty_2Ety__2Elist__2Elist, type,
    ty_2Elist_2Elist : $tType > $tType).
tff(sy_2Epxy__2Eeq, type,
    pxy_2Eeq : !>[A_27a : $tType]: (A_27a > A_27a > $o)).
tff(sy_2Ec__2Ebool__2ECOND, type,
    c_2Ebool_2ECOND : ($o * ty_2Enum_2Enum * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2Epxy__2Enot, type,
    pxy_2Enot : $o > $o).
tff(sy_2Ec__2Elist__2ENIL, type,
    c_2Elist_2ENIL : !>[A_27a : $tType]: ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a))).
tff(sy_2Epxy__2Etrue, type,
    pxy_2Etrue : $o).
tff(sy_2Epxy__2Efalse, type,
    pxy_2Efalse : $o).
tff(sy_2Eapp, type,
    app_2E : ($i * $i) > $i).
tff(sy_2EV__lam__2E0, type,
    V_lam_2E0 : ty_2Enum_2Enum > ty_2Enum_2Enum).
tff(sy_2EV__lam__2E1, type,
    V_lam_2E1 : ty_2Enum_2Enum > ty_2Enum_2Enum).
tff(sy_2EV__use____bool, type,
    V_use__bool : $o > $o).
tff(sy_2Epxy__2Enot, type,
    pxy_2Enot : $o > $o).
tff(sy_2EHX, type,
    HX : ty_2Enum_2Enum > ty_2Enum_2Enum).
tff(sy_2EHY, type,
    HY : ty_2Enum_2Enum > ty_2Enum_2Enum).
tff(sy_2EV__f, type,
    V_f : A_27a > A_27b).
tff(sy_2EV__g, type,
    V_g : A_27a > A_27b).
tff(sy_2Epp, type,
    pp_2E : $i > $o).
% Helpers (17)
tff(help_2Eif__True, axiom,
    ((!>[A_27a : $tType]: (![HX : A_27a]: (![HY : A_27a]: pxy_2Eeq(A_27a,c_2Ebool_2ECOND(A_27a,A_27a,pp_2E(pxy_2Etrue),HX,HY),HX)))))).
tff(help_2Eif__False, axiom,
    ((!>[A_27a : $tType]: (![HX : A_27a]: (![HY : A_27a]: pxy_2Eeq(A_27a,c_2Ebool_2ECOND(A_27a,A_27a,pp_2E(pxy_2Efalse),HX,HY),HY)))))).
tff(help_2Ebool__cases, axiom,
    ((![HB : $o]: ((HB <=> pxy_2Etrue) | (HB <=> pxy_2Efalse))))).
tff(help_2Epxy_2Eeq, axiom,
    ((!>[A_27a : $tType]: (![HX : ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a))]: (![HY : ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a))]: (pxy_2Eeq(ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a)),HX,HY) => pxy_2Eeq(ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a)),HX,HY))))))).
tff(help_2Epxy_2Eeq_2E2, axiom,
    ((!>[A_27a : $tType]: (![HX : ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a))]: (![HY : ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a))]: (pxy_2Eeq(ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a)),HX,HY) => pxy_2Eeq(ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a)),HX,HY))))))).
tff(help_2Epxy_2Eeq_2E3, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: (pxy_2Eeq(ty_2Enum_2Enum,HX,HY) => pxy_2Eeq(ty_2Enum_2Enum,HX,HY)))))).
tff(help_2Epxy_2Eeq_2E4, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: (pxy_2Eeq(ty_2Enum_2Enum,HX,HY) => pxy_2Eeq(ty_2Enum_2Enum,HX,HY)))))).
tff(help_2Epxy_2Eeq_2E5, axiom,
    ((!>[A_27a : $tType]: (![HX : A_27a]: (![HY : A_27a]: (pxy_2Eeq(A_27a,HX,HY) => pxy_2Eeq(A_27a,HX,HY))))))).
tff(help_2Epxy_2Eeq_2E6, axiom,
    ((!>[A_27a : $tType]: (![HX : A_27a]: (![HY : A_27a]: (pxy_2Eeq(A_27a,HX,HY) => pxy_2Eeq(A_27a,HX,HY))))))).
tff(help_2Epxy_2Etrue, axiom,
    ((pxy_2Etrue <=> pxy_2Etrue))).
tff(help_2Epxy_2Efalse, axiom,
    ((pxy_2Efalse <=> pxy_2Efalse))).
tff(help_2Epxy_2Eeq_2E7, axiom,
    ((![HX : ty_2Enum_2Enum > ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum > ty_2Enum_2Enum]: (pxy_2Eeq(ty_2Enum_2Enum > ty_2Enum_2Enum,HX,HY) => pxy_2Eeq(ty_2Enum_2Enum > ty_2Enum_2Enum,HX,HY)))))).
tff(help_2Epxy_2Eeq_2E8, axiom,
    ((![HX : ty_2Enum_2Enum > ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum > ty_2Enum_2Enum]: (pxy_2Eeq(ty_2Enum_2Enum > ty_2Enum_2Enum,HX,HY) => pxy_2Eeq(ty_2Enum_2Enum > ty_2Enum_2Enum,HX,HY)))))).
tff(help_2Epxy_2Enot, axiom,
    ((![HP : $o]: (app_2E(pxy_2Enot,pp_2E(HP)) <=> (~ HP))))).
tff(help_2Eeq__ext, axiom,
    ((!>[A_27a : $tType, A_27b : $tType]: (![V_f : A_27a > A_27b]: (![V_g : A_27a > A_27b]: ((![V_x : A_27a]: pxy_2Eeq(A_27b,app_2E(V_f,V_x),app_2E(V_g,V_x))) => pxy_2Eeq(A_27a > A_27b,V_f,V_g))))))).
tff(help_2Epp_2Etrue, axiom,
    (pp_2E(pxy_2Etrue))).
tff(help_2Epp_2Efalse, axiom,
    ((~ pp_2E(pxy_2Efalse)))).
% Facts (3)
tff(thm_2Epoly, axiom,
    ((!>[A_27a : $tType]: (pxy_2Eeq(ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a)),c_2Elist_2ENIL(ty_2Elist_2Elist(A_27a)),c_2Elist_2ENIL(ty_2Elist_2Elist(A_27a))) <=> pxy_2Eeq(ty_2Elist_2Elist(ty_2Elist_2Elist(A_27a)),c_2Elist_2ENIL(ty_2Elist_2Elist(A_27a)),c_2Elist_2ENIL(ty_2Elist_2Elist(A_27a))))))).
tff(lam_2E0, axiom,
    ((![X : ty_2Enum_2Enum]: pxy_2Eeq(ty_2Enum_2Enum,app_2E(V_lam_2E0,X),X)))).
tff(lam_2E1, axiom,
    ((![X : ty_2Enum_2Enum]: pxy_2Eeq(ty_2Enum_2Enum,app_2E(V_lam_2E1,X),X)))).
% Conjecture (1)
tff(conjecture, conjecture,
    ((![P : $o]: (![X : ty_2Enum_2Enum]: (![Y : ty_2Enum_2Enum]: (![V_use__bool : $o > $o]: (pxy_2Eeq(ty_2Enum_2Enum,app_2E(c_2Ebool_2ECOND(ty_2Enum_2Enum,pp_2E(P),X),Y),X) & (pxy_2Eeq(ty_2Enum_2Enum > ty_2Enum_2Enum,V_lam_2E0,V_lam_2E1) & (app_2E(V_use__bool,pp_2E(app_2E(pxy_2Enot,pp_2E(P)))) & pxy_2Eeq(ty_2Enum_2Enum,X,X)))))))))).
