% generated by hhProblemGen; format=thf; type_enc=mono_native_higher_fool; lam_trans=keep_lams; mono_iters=3; mono_instances=100
% Declarations (14)
thf(ty_2Ety__2Emin__2Ebool, type,
    ty_2Emin_2Ebool : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : $tType).
thf(ty_2Ety__2Enum__2Enum, type,
    ty_2Enum_2Enum : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
thf(sy_2Epxy__2Eeq__2Enum__2Enum, type,
    pxy_2Eeq_2Enum_2Enum : ty_2Enum_2Enum > ty_2Enum_2Enum > $o).
thf(sy_2Epxy__2Eite__2Enum__2Enum, type,
    pxy_2Eite_2Enum_2Enum : $o > ty_2Enum_2Enum > ty_2Enum_2Enum > ty_2Enum_2Enum).
thf(sy_2Epxy__2Eeq__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : (ty_2Enum_2Enum > ty_2Enum_2Enum) > (ty_2Enum_2Enum > ty_2Enum_2Enum) > $o).
thf(sy_2Epxy__2Enot, type,
    pxy_2Enot : $o > $o).
% Helpers (5)
thf(help_2Epxy_2Eeq, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: ((pxy_2Eeq_2Enum_2Enum @ HX @ HY) => (pxy_2Eeq_2Enum_2Enum @ HX @ HY)))))).
thf(help_2Epxy_2Eeq_2E2, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: ((pxy_2Eeq_2Enum_2Enum @ HX @ HY) => (pxy_2Eeq_2Enum_2Enum @ HX @ HY)))))).
thf(help_2Epxy_2Eeq_2E3, axiom,
    ((![HX : ty_2Enum_2Enum > ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum > ty_2Enum_2Enum]: ((pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ HX @ HY) => (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ HX @ HY)))))).
thf(help_2Epxy_2Eeq_2E4, axiom,
    ((![HX : ty_2Enum_2Enum > ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum > ty_2Enum_2Enum]: ((pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ HX @ HY) => (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ HX @ HY)))))).
thf(help_2Epxy_2Enot, axiom,
    ((![HP : $o]: ((pxy_2Enot @ HP) <=> (~ HP))))).
% Facts (0)
% Conjecture (1)
thf(conjecture, conjecture,
    ((![P : $o]: (![X : ty_2Enum_2Enum]: (![Y : ty_2Enum_2Enum]: (![V_use__bool : $o > $o]: ((pxy_2Eeq_2Enum_2Enum @ $ite(P,X,Y) @ X) & ((pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ (^[X : ty_2Enum_2Enum]: X) @ (^[X : ty_2Enum_2Enum]: X)) & ((V_use__bool @ (pxy_2Enot @ P)) & (pxy_2Eeq_2Enum_2Enum @ X @ X)))))))))).
