% generated by hhProblemGen; format=fof; type_enc=mono_guards??; lam_trans=lifting; mono_iters=3; mono_instances=100
% Declarations (10)
fof(gsy_2Epxy__2Eeq__2Enum__2Enum, axiom,
    ((![G0, G1]: gd_2Ety__2Emin__2Ebool(pxy_2Eeq_2Enum_2Enum(G0,G1))))).
fof(gsy_2Epxy__2Eeq__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, axiom,
    ((![G0, G1]: gd_2Ety__2Emin__2Ebool(pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(G0,G1))))).
fof(gsy_2Epxy__2Enot, axiom,
    ((![G0]: gd_2Ety__2Emin__2Ebool(pxy_2Enot(G0))))).
fof(gsy_2Ec__2Ebool__2ECOND__2Emin__2Ebool, axiom,
    ((![G0, G1, G2]: gd_2Ety__2Emin__2Ebool(c_2Ebool_2ECOND_2Emin_2Ebool(G0,G1,G2))))).
fof(gsy_2Epxy__2Etrue, axiom,
    (gd_2Ety__2Emin__2Ebool(pxy_2Etrue))).
fof(gsy_2Epxy__2Eeq__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, axiom,
    ((![G0, G1]: gd_2Ety__2Emin__2Ebool(pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(G0,G1))))).
fof(gsy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, axiom,
    ((![G0, G1, G2, G3]: gd_2Ety__2Emin__2Ebool(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(G0,G1,G2,G3))))).
fof(gsy_2Epxy__2Efalse, axiom,
    (gd_2Ety__2Emin__2Ebool(pxy_2Efalse))).
fof(wit_2Ety__2Emin__2Ebool, axiom,
    (gd_2Ety__2Emin__2Ebool(wit_2Ety__2Emin__2Ebool))).
fof(wit_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, axiom,
    (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(wit_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29))).
% Helpers (22)
fof(help_2Eif__True, axiom,
    ((![HX]: (gd_2Ety__2Emin__2Ebool(HX) => (![HY]: (gd_2Ety__2Emin__2Ebool(HY) => (app_2E(c_2Ebool_2ECOND_2Emin_2Ebool(pp_2E(pxy_2Etrue),pp_2E(HX)),pp_2E(HY)) <=> HX))))))).
fof(help_2Eif__True_2E2, axiom,
    ((![HX]: (![HY]: pxy_2Eeq_2Enum_2Enum(app_2E(c_2Ebool_2ECOND_2Enum_2Enum(pp_2E(pxy_2Etrue),HX),HY),HX))))).
fof(help_2Eif__True_2E3, axiom,
    ((![HX]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(HX) => (![HY]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(HY) => pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(pp_2E(pxy_2Etrue),HX,HY),HX))))))).
fof(help_2Eif__True_2E4, axiom,
    ((![HX]: (![HY]: pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(pp_2E(pxy_2Etrue),HX,HY),HX))))).
fof(help_2Eif__False, axiom,
    ((![HX]: (gd_2Ety__2Emin__2Ebool(HX) => (![HY]: (gd_2Ety__2Emin__2Ebool(HY) => (app_2E(c_2Ebool_2ECOND_2Emin_2Ebool(pp_2E(pxy_2Efalse),pp_2E(HX)),pp_2E(HY)) <=> HY))))))).
fof(help_2Eif__False_2E2, axiom,
    ((![HX]: (![HY]: pxy_2Eeq_2Enum_2Enum(app_2E(c_2Ebool_2ECOND_2Enum_2Enum(pp_2E(pxy_2Efalse),HX),HY),HY))))).
fof(help_2Eif__False_2E3, axiom,
    ((![HX]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(HX) => (![HY]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(HY) => pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(pp_2E(pxy_2Efalse),HX,HY),HY))))))).
fof(help_2Eif__False_2E4, axiom,
    ((![HX]: (![HY]: pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(pp_2E(pxy_2Efalse),HX,HY),HY))))).
fof(help_2Ebool__cases, axiom,
    ((![HB]: (gd_2Ety__2Emin__2Ebool(HB) => ((HB <=> pxy_2Etrue) | (HB <=> pxy_2Efalse)))))).
fof(help_2Epxy_2Eeq, axiom,
    ((![HX]: (![HY]: (pxy_2Eeq_2Enum_2Enum(HX,HY) => pxy_2Eeq_2Enum_2Enum(HX,HY)))))).
fof(help_2Epxy_2Eeq_2E2, axiom,
    ((![HX]: (![HY]: (pxy_2Eeq_2Enum_2Enum(HX,HY) => pxy_2Eeq_2Enum_2Enum(HX,HY)))))).
fof(help_2Epxy_2Etrue, axiom,
    ((pxy_2Etrue <=> pxy_2Etrue))).
fof(help_2Epxy_2Eeq_2E3, axiom,
    ((![HX]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(HX) => (![HY]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(HY) => (pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(HX,HY) => pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(HX,HY)))))))).
fof(help_2Epxy_2Eeq_2E4, axiom,
    ((![HX]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(HX) => (![HY]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(HY) => (pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(HX,HY) => pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(HX,HY)))))))).
fof(help_2Epxy_2Eeq_2E5, axiom,
    ((![HX]: (![HY]: (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(HX,HY) => pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(HX,HY)))))).
fof(help_2Epxy_2Eeq_2E6, axiom,
    ((![HX]: (![HY]: (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(HX,HY) => pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(HX,HY)))))).
fof(help_2Epxy_2Efalse, axiom,
    ((pxy_2Efalse <=> pxy_2Efalse))).
fof(help_2Epxy_2Enot, axiom,
    ((![HP]: (gd_2Ety__2Emin__2Ebool(HP) => (app_2E(pxy_2Enot,pp_2E(HP)) <=> (~ HP)))))).
fof(help_2Eeq__ext, axiom,
    ((![V_f]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(V_f) => (![V_g]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(V_g) => ((![V_x]: (gd_2Ety__2Emin__2Ebool(V_x) => (app_2E(V_f,pp_2E(V_x)) <=> app_2E(V_g,pp_2E(V_x))))) => pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(V_f,V_g)))))))).
fof(help_2Eeq__ext_2E2, axiom,
    ((![V_f]: (![V_g]: ((![V_x]: pxy_2Eeq_2Enum_2Enum(app_2E(V_f,V_x),app_2E(V_g,V_x))) => pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(V_f,V_g)))))).
fof(help_2Epp_2Etrue, axiom,
    (pp_2E(pxy_2Etrue))).
fof(help_2Epp_2Efalse, axiom,
    ((~ pp_2E(pxy_2Efalse)))).
% Facts (2)
fof(lam_2E0, axiom,
    ((![X]: pxy_2Eeq_2Enum_2Enum(app_2E(V_lam_2E0,X),X)))).
fof(lam_2E1, axiom,
    ((![X]: pxy_2Eeq_2Enum_2Enum(app_2E(V_lam_2E1,X),X)))).
% Conjecture (1)
fof(conjecture, conjecture,
    ((![P]: (gd_2Ety__2Emin__2Ebool(P) => (![X]: (![Y]: (![V_use__bool]: (gd_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29(V_use__bool) => (pxy_2Eeq_2Enum_2Enum(app_2E(c_2Ebool_2ECOND_2Enum_2Enum(pp_2E(P),X),Y),X) & (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(V_lam_2E0,V_lam_2E1) & (app_2E(V_use__bool,pp_2E(app_2E(pxy_2Enot,pp_2E(P)))) & pxy_2Eeq_2Enum_2Enum(X,X)))))))))))).
