% generated by hhProblemGen; format=thf; type_enc=mono_native_higher; lam_trans=keep_lams; mono_iters=3; mono_instances=100
% Declarations (28)
thf(ty_2Ety__2Emin__2Ebool, type,
    ty_2Emin_2Ebool : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : $tType).
thf(ty_2Ety__2Enum__2Enum, type,
    ty_2Enum_2Enum : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29 : $tType).
thf(sy_2Epxy__2Eeq__2Enum__2Enum, type,
    pxy_2Eeq_2Enum_2Enum : ty_2Enum_2Enum > ty_2Enum_2Enum > $o).
thf(sy_2Ec__2Ebool__2ECOND__2Enum__2Enum, type,
    c_2Ebool_2ECOND_2Enum_2Enum : $o > ty_2Enum_2Enum > ty_2Enum_2Enum > ty_2Enum_2Enum).
thf(sy_2Epxy__2Eeq__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : (ty_2Enum_2Enum > ty_2Enum_2Enum) > (ty_2Enum_2Enum > ty_2Enum_2Enum) > $o).
thf(sy_2Epxy__2Enot, type,
    pxy_2Enot : $o > $o).
thf(sy_2Ec__2Ebool__2ECOND__2Emin__2Ebool, type,
    c_2Ebool_2ECOND_2Emin_2Ebool : $o > $o > $o > $o).
thf(sy_2Epxy__2Eeq__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : ($o > $o) > ($o > $o) > $o).
thf(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : $o > ($o > $o) > ($o > $o) > $o > $o).
thf(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : $o > (ty_2Enum_2Enum > ty_2Enum_2Enum) > (ty_2Enum_2Enum > ty_2Enum_2Enum) > ty_2Enum_2Enum > ty_2Enum_2Enum).
% Helpers (16)
thf(help_2Eif__True, axiom,
    ((![HX : $o]: (![HY : $o]: ((c_2Ebool_2ECOND_2Emin_2Ebool @ $true @ HX @ HY) <=> HX))))).
thf(help_2Eif__True_2E2, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: (pxy_2Eeq_2Enum_2Enum @ (c_2Ebool_2ECOND_2Enum_2Enum @ $true @ HX @ HY) @ HX))))).
thf(help_2Eif__True_2E3, axiom,
    ((![HX : $o > $o]: (![HY : $o > $o]: (pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 @ (c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 @ $true @ HX @ HY) @ HX))))).
thf(help_2Eif__True_2E4, axiom,
    ((![HX : ty_2Enum_2Enum > ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum > ty_2Enum_2Enum]: (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ (c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ $true @ HX @ HY) @ HX))))).
thf(help_2Eif__False, axiom,
    ((![HX : $o]: (![HY : $o]: ((c_2Ebool_2ECOND_2Emin_2Ebool @ $false @ HX @ HY) <=> HY))))).
thf(help_2Eif__False_2E2, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: (pxy_2Eeq_2Enum_2Enum @ (c_2Ebool_2ECOND_2Enum_2Enum @ $false @ HX @ HY) @ HY))))).
thf(help_2Eif__False_2E3, axiom,
    ((![HX : $o > $o]: (![HY : $o > $o]: (pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 @ (c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 @ $false @ HX @ HY) @ HY))))).
thf(help_2Eif__False_2E4, axiom,
    ((![HX : ty_2Enum_2Enum > ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum > ty_2Enum_2Enum]: (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ (c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ $false @ HX @ HY) @ HY))))).
thf(help_2Ebool__cases, axiom,
    ((![HB : $o]: ((HB <=> $true) | (HB <=> $false))))).
thf(help_2Epxy_2Eeq, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: ((pxy_2Eeq_2Enum_2Enum @ HX @ HY) => (pxy_2Eeq_2Enum_2Enum @ HX @ HY)))))).
thf(help_2Epxy_2Eeq_2E2, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: ((pxy_2Eeq_2Enum_2Enum @ HX @ HY) => (pxy_2Eeq_2Enum_2Enum @ HX @ HY)))))).
thf(help_2Epxy_2Eeq_2E3, axiom,
    ((![HX : $o > $o]: (![HY : $o > $o]: ((pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 @ HX @ HY) => (pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 @ HX @ HY)))))).
thf(help_2Epxy_2Eeq_2E4, axiom,
    ((![HX : $o > $o]: (![HY : $o > $o]: ((pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 @ HX @ HY) => (pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 @ HX @ HY)))))).
thf(help_2Epxy_2Eeq_2E5, axiom,
    ((![HX : ty_2Enum_2Enum > ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum > ty_2Enum_2Enum]: ((pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ HX @ HY) => (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ HX @ HY)))))).
thf(help_2Epxy_2Eeq_2E6, axiom,
    ((![HX : ty_2Enum_2Enum > ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum > ty_2Enum_2Enum]: ((pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ HX @ HY) => (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ HX @ HY)))))).
thf(help_2Epxy_2Enot, axiom,
    ((![HP : $o]: ((pxy_2Enot @ HP) <=> (~ HP))))).
% Facts (0)
% Conjecture (1)
thf(conjecture, conjecture,
    ((![P : $o]: (![X : ty_2Enum_2Enum]: (![Y : ty_2Enum_2Enum]: (![V_use__bool : $o > $o]: ((pxy_2Eeq_2Enum_2Enum @ (c_2Ebool_2ECOND_2Enum_2Enum @ P @ X @ Y) @ X) & ((pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ (^[X : ty_2Enum_2Enum]: X) @ (^[X : ty_2Enum_2Enum]: X)) & ((V_use__bool @ (pxy_2Enot @ P)) & (pxy_2Eeq_2Enum_2Enum @ X @ X)))))))))).
