% generated by hhProblemGen; format=tff; type_enc=mono_native_fool; lam_trans=combs; mono_iters=3; mono_instances=100
% Declarations (39)
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Enum__2Enum, type,
    ty_2Enum_2Enum : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Ebool, type,
    ty_2Emin_2Ebool : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(sy_2Epxy__2Eeq__2Enum__2Enum, type,
    pxy_2Eeq_2Enum_2Enum : (ty_2Enum_2Enum * ty_2Enum_2Enum) > $o).
tff(sy_2Epxy__2Eite__2Enum__2Enum, type,
    pxy_2Eite_2Enum_2Enum : ($o * ty_2Enum_2Enum * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2Epxy__2Eeq__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : (ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 * ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29) > $o).
tff(sy_2Ec__2Ecombin__2EI__2Enum__2Enum, type,
    c_2Ecombin_2EI_2Enum_2Enum : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29).
tff(sy_2Epxy__2Enot, type,
    pxy_2Enot : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Ebool, type,
    c_2Ecombin_2EI_2Emin_2Ebool : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Epxy__2Eeq__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : (ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29) > $o).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    c_2Ecombin_2EI_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 > ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    c_2Ecombin_2EI_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 > ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29).
tff(sy_2Eapp__9ef68b7b5caf32d0, type,
    app_9ef68b7b5caf32d0 : (ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 * $o) > $o).
tff(sy_2Eapp__d0ff6e03f6af4465, type,
    app_d0ff6e03f6af4465 : (ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2Evalue__c__2Ecombin__2EI__1b0979bea8bd, type,
    value_c_2Ecombin_2EI_1b0979bea8bd : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29).
tff(sy_2Evalue__use____bool__52be863679c4, type,
    value_use__bool_52be863679c4 : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Evalue__pxy__2Enot__52be863679c4, type,
    value_pxy_2Enot_52be863679c4 : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Evalue__c__2Ecombin__2EI__52be863679c4, type,
    value_c_2Ecombin_2EI_52be863679c4 : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Evalue__x__52be863679c4, type,
    value_x_52be863679c4 : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Evalue__x__1b0979bea8bd, type,
    value_x_1b0979bea8bd : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29).
tff(sy_2Evalue__HX__52be863679c4, type,
    value_HX_52be863679c4 : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Evalue__HY__52be863679c4, type,
    value_HY_52be863679c4 : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Evalue__HX__1b0979bea8bd, type,
    value_HX_1b0979bea8bd : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29).
tff(sy_2Evalue__HY__1b0979bea8bd, type,
    value_HY_1b0979bea8bd : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29).
tff(sy_2Evalue__f__52be863679c4, type,
    value_f_52be863679c4 : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Evalue__g__52be863679c4, type,
    value_g_52be863679c4 : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29).
tff(sy_2Evalue__f__1b0979bea8bd, type,
    value_f_1b0979bea8bd : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29).
tff(sy_2Evalue__g__1b0979bea8bd, type,
    value_g_1b0979bea8bd : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29).
% Helpers (13)
tff(help_2Ecombin_2EI, axiom,
    ((![V_x : $o]: (app_9ef68b7b5caf32d0(value_c_2Ecombin_2EI_52be863679c4,V_x) <=> V_x)))).
tff(help_2Ecombin_2EI_2E2, axiom,
    ((![V_x : ty_2Enum_2Enum]: pxy_2Eeq_2Enum_2Enum(app_d0ff6e03f6af4465(value_c_2Ecombin_2EI_1b0979bea8bd,V_x),V_x)))).
tff(help_2Ecombin_2EI_2E3, axiom,
    ((![V_x : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(c_2Ecombin_2EI_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(value_x_52be863679c4),value_x_52be863679c4)))).
tff(help_2Ecombin_2EI_2E4, axiom,
    ((![V_x : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(c_2Ecombin_2EI_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(value_x_1b0979bea8bd),value_x_1b0979bea8bd)))).
tff(help_2Epxy_2Eeq, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: (pxy_2Eeq_2Enum_2Enum(HX,HY) => pxy_2Eeq_2Enum_2Enum(HX,HY)))))).
tff(help_2Epxy_2Eeq_2E2, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: (pxy_2Eeq_2Enum_2Enum(HX,HY) => pxy_2Eeq_2Enum_2Enum(HX,HY)))))).
tff(help_2Epxy_2Eeq_2E3, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(value_HX_52be863679c4,value_HY_52be863679c4) => pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(value_HX_52be863679c4,value_HY_52be863679c4)))))).
tff(help_2Epxy_2Eeq_2E4, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(value_HX_52be863679c4,value_HY_52be863679c4) => pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(value_HX_52be863679c4,value_HY_52be863679c4)))))).
tff(help_2Epxy_2Eeq_2E5, axiom,
    ((![HX : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (![HY : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(value_HX_1b0979bea8bd,value_HY_1b0979bea8bd) => pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(value_HX_1b0979bea8bd,value_HY_1b0979bea8bd)))))).
tff(help_2Epxy_2Eeq_2E6, axiom,
    ((![HX : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (![HY : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(value_HX_1b0979bea8bd,value_HY_1b0979bea8bd) => pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(value_HX_1b0979bea8bd,value_HY_1b0979bea8bd)))))).
tff(help_2Epxy_2Enot, axiom,
    ((![HP : $o]: (app_9ef68b7b5caf32d0(value_pxy_2Enot_52be863679c4,HP) <=> (~ HP))))).
tff(help_2Eeq__ext, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: ((![V_x : $o]: (app_9ef68b7b5caf32d0(value_f_52be863679c4,V_x) <=> app_9ef68b7b5caf32d0(value_g_52be863679c4,V_x))) => pxy_2Eeq_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(value_f_52be863679c4,value_g_52be863679c4)))))).
tff(help_2Eeq__ext_2E2, axiom,
    ((![V_f : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: ((![V_x : ty_2Enum_2Enum]: pxy_2Eeq_2Enum_2Enum(app_d0ff6e03f6af4465(value_f_1b0979bea8bd,V_x),app_d0ff6e03f6af4465(value_g_1b0979bea8bd,V_x))) => pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(value_f_1b0979bea8bd,value_g_1b0979bea8bd)))))).
% Facts (0)
% Conjecture (1)
tff(conjecture, conjecture,
    ((![P : $o]: (![X : ty_2Enum_2Enum]: (![Y : ty_2Enum_2Enum]: (![V_use__bool : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (pxy_2Eeq_2Enum_2Enum($ite(P,X,Y),X) & (pxy_2Eeq_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(value_c_2Ecombin_2EI_1b0979bea8bd,value_c_2Ecombin_2EI_1b0979bea8bd) & (app_9ef68b7b5caf32d0(value_use__bool_52be863679c4,app_9ef68b7b5caf32d0(value_pxy_2Enot_52be863679c4,P)) & pxy_2Eeq_2Enum_2Enum(X,X)))))))))).
