% generated by hhProblemGen; format=tff; type_enc=mono_native_fool; lam_trans=lifting; mono_iters=3; mono_instances=100
% Declarations (48)
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Enum__2Enum, type,
    ty_2Enum_2Enum : $tType).
tff(ty_2Ety__2Emin__2Ebool, type,
    ty_2Emin_2Ebool : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Enum_2Enum * ty_2Enum_2Enum) > ty_2Emin_2Ebool).
tff(sy_2E__24ite, type,
    _24ite : (ty_2Emin_2Ebool * ty_2Enum_2Enum * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 * ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29) > ty_2Emin_2Ebool).
tff(sy_2E__24not, type,
    _24not : ty_2Emin_2Ebool > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29 * ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29 * ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29 * ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29) > ty_2Emin_2Ebool).
tff(sy_2E__24equal, type,
    _24equal : (ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 * ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29) > ty_2Emin_2Ebool).
tff(sy_2Eapp, type,
    app_2E : ($i * $i) > $i).
% Helpers (10)
tff(help_2Eeq__ext, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: ((![V_x : ty_2Emin_2Ebool]: (app_2E(V_f,V_x) <=> app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E2, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: ((![V_x : ty_2Emin_2Ebool]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E3, axiom,
    ((![V_f : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: ((![V_x : ty_2Enum_2Enum]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E4, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: ((![V_x : ty_2Emin_2Ebool]: _24equal(app_2E(V_f,V_x),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E5, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: ((![V_x : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E6, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cnum_2Enum_29]: ((![V_x : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E7, axiom,
    ((![V_f : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![V_g : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: ((![V_x : ty_2Enum_2Enum]: _24equal(app_2E(V_f,V_x),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E8, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![V_g : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: ((![V_x : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: _24equal(app_2E(V_f,V_x),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E9, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![V_g : ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: ((![V_x : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: _24equal(app_2E(V_f,V_x),app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
tff(help_2Eeq__ext_2E10, axiom,
    ((![V_f : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: (![V_g : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: ((![V_x : ty_2Enum_2Enum]: (app_2E(V_f,V_x) <=> app_2E(V_g,V_x))) => _24equal(V_f,V_g)))))).
% Facts (2)
tff(lam_2E0, axiom,
    ((![X : ty_2Enum_2Enum]: _24equal(app_2E(V_lam_2E0,X),X)))).
tff(lam_2E1, axiom,
    ((![X : ty_2Enum_2Enum]: _24equal(app_2E(V_lam_2E1,X),X)))).
% Conjecture (1)
tff(conjecture, conjecture,
    ((![P : ty_2Emin_2Ebool]: (![X : ty_2Enum_2Enum]: (![Y : ty_2Enum_2Enum]: (![V_use__bool : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (_24equal(_24ite(P,X,Y),X) & (_24equal(V_lam_2E0,V_lam_2E1) & (app_2E(V_use__bool,app_2E(_24not,P)) & _24equal(X,X)))))))))).
