% generated by hhProblemGen; format=tff; type_enc=mono_native_fool; lam_trans=combs; mono_iters=3; mono_instances=100
% Declarations (53)
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Ebool, type,
    ty_2Emin_2Ebool : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Enum__2Enum, type,
    ty_2Enum_2Enum : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cnum__2Enum__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cnum_2Enum_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cnum__2Enum__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cnum_2Enum_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Ebool_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Ebool__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Ebool_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29 : $tType).
tff(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
tff(sy_2Ec__2Ecombin__2EI__2Enum__2Enum, type,
    c_2Ecombin_2EI_2Enum_2Enum : ty_2Enum_2Enum > ty_2Enum_2Enum).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Ebool, type,
    c_2Ecombin_2EI_2Emin_2Ebool : ty_2Emin_2Ebool > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    c_2Ecombin_2EI_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : (ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 * ty_2Emin_2Ebool) > ty_2Emin_2Ebool).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    c_2Ecombin_2EI_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : (ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Efun__28min__2Ebool__2Cnum__2Enum__29, type,
    c_2Ecombin_2EI_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29 : (ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29 * ty_2Emin_2Ebool) > ty_2Enum_2Enum).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    c_2Ecombin_2EI_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : (ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Emin_2Ebool * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cnum__2Enum__29, type,
    c_2Ecombin_2EI_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29 : (ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29) > ty_2Enum_2Enum).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    c_2Ecombin_2EI_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : (ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Enum_2Enum * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    c_2Ecombin_2EI_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : (ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 * ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 * ty_2Enum_2Enum) > ty_2Enum_2Enum).
tff(sy_2Ec__2Ecombin__2EI__2Emin__2Efun__28num__2Enum__2Cmin__2Ebool__29, type,
    c_2Ecombin_2EI_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 : (ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 * ty_2Enum_2Enum) > ty_2Emin_2Ebool).
tff(sy_2Eapp, type,
    app_2E : ($i * $i) > $i).
% Helpers (20)
tff(help_2Ecombin_2EI, axiom,
    ((![V_x : ty_2Emin_2Ebool]: (app_2E(c_2Ecombin_2EI_2Emin_2Ebool,V_x) <=> V_x)))).
tff(help_2Ecombin_2EI_2E2, axiom,
    ((![V_x : ty_2Enum_2Enum]: app_2E(_24equal(app_2E(c_2Ecombin_2EI_2Enum_2Enum,V_x)),V_x)))).
tff(help_2Ecombin_2EI_2E3, axiom,
    ((![V_x : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (c_2Ecombin_2EI_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29(V_x) = V_x)))).
tff(help_2Ecombin_2EI_2E4, axiom,
    ((![V_x : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (c_2Ecombin_2EI_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29(V_x) = V_x)))).
tff(help_2Ecombin_2EI_2E5, axiom,
    ((![V_x : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: (c_2Ecombin_2EI_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29(V_x) = V_x)))).
tff(help_2Ecombin_2EI_2E6, axiom,
    ((![V_x : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (c_2Ecombin_2EI_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29(V_x) = V_x)))).
tff(help_2Ecombin_2EI_2E7, axiom,
    ((![V_x : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: (c_2Ecombin_2EI_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29(V_x) = V_x)))).
tff(help_2Ecombin_2EI_2E8, axiom,
    ((![V_x : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (c_2Ecombin_2EI_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29(V_x) = V_x)))).
tff(help_2Ecombin_2EI_2E9, axiom,
    ((![V_x : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (c_2Ecombin_2EI_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29(V_x) = V_x)))).
tff(help_2Ecombin_2EI_2E10, axiom,
    ((![V_x : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: (c_2Ecombin_2EI_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29(V_x) = V_x)))).
tff(help_2Eeq__ext, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: ((![V_x : ty_2Emin_2Ebool]: (app_2E(V_f,V_x) <=> app_2E(V_g,V_x))) => (V_f = V_g)))))).
tff(help_2Eeq__ext_2E2, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cnum_2Enum_29]: ((![V_x : ty_2Emin_2Ebool]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => (V_f = V_g)))))).
tff(help_2Eeq__ext_2E3, axiom,
    ((![V_f : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: ((![V_x : ty_2Enum_2Enum]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => (V_f = V_g)))))).
tff(help_2Eeq__ext_2E4, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: ((![V_x : ty_2Emin_2Ebool]: (app_2E(V_f,V_x) = app_2E(V_g,V_x))) => (V_f = V_g)))))).
tff(help_2Eeq__ext_2E5, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: (![V_g : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cnum_2Enum_29]: ((![V_x : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: app_2E(_24equal(app_2E(V_f,V_x)),app_2E(V_g,V_x))) => (V_f = V_g)))))).
tff(help_2Eeq__ext_2E6, axiom,
    ((![V_f : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![V_g : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: ((![V_x : ty_2Enum_2Enum]: (app_2E(V_f,V_x) = app_2E(V_g,V_x))) => (V_f = V_g)))))).
tff(help_2Eeq__ext_2E7, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: (![V_g : ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29]: ((![V_x : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (app_2E(V_f,V_x) = app_2E(V_g,V_x))) => (V_f = V_g)))))).
tff(help_2Eeq__ext_2E8, axiom,
    ((![V_f : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: (![V_g : ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29]: ((![V_x : ty_2Enum_2Enum]: (app_2E(V_f,V_x) <=> app_2E(V_g,V_x))) => (V_f = V_g)))))).
tff(help_2Eeq__ext_2E9, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29]: ((![V_x : ty_2Emin_2Ebool]: (app_2E(V_f,V_x) = app_2E(V_g,V_x))) => (V_f = V_g)))))).
tff(help_2Eeq__ext_2E10, axiom,
    ((![V_f : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cnum_2Enum_29_29]: (![V_g : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cnum_2Enum_29_29]: ((![V_x : ty_2Emin_2Ebool]: (app_2E(V_f,V_x) = app_2E(V_g,V_x))) => (V_f = V_g)))))).
% Facts (0)
% Conjecture (1)
tff(conjecture, conjecture,
    ((![P : ty_2Emin_2Ebool]: (![X : ty_2Enum_2Enum]: (![Y : ty_2Enum_2Enum]: (![V_use__bool : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (app_2E(_24equal(app_2E(_24ite_2Enum_2Enum(P,X),Y)),X) & ((c_2Ecombin_2EI_2Enum_2Enum = c_2Ecombin_2EI_2Enum_2Enum) & (app_2E(V_use__bool,app_2E(_24not,P)) & app_2E(_24equal(X),X)))))))))).
