% generated by hhProblemGen; format=thf; type_enc=mono_native_higher; lam_trans=keep_lams; mono_iters=3; mono_instances=100
% Declarations (30)
thf(ty_2Ety__2Emin__2Ebool, type,
    ty_2Emin_2Ebool : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : $tType).
thf(ty_2Ety__2Enum__2Enum, type,
    ty_2Enum_2Enum : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28num__2Enum__2Cnum__2Enum__29__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28num_2Enum_2Cnum_2Enum_29_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Efun__28min__2Ebool__2Cmin__2Ebool__29__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Efun_28min_2Ebool_2Cmin_2Ebool_29_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cmin_2Ebool_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Ebool__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Ebool_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28num__2Enum__2Cmin__2Efun__28num__2Enum__2Cnum__2Enum__29__29, type,
    ty_2Emin_2Efun_28num_2Enum_2Cmin_2Efun_28num_2Enum_2Cnum_2Enum_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29_29 : $tType).
thf(ty_2Ety__2Emin__2Efun__28min__2Ebool__2Cmin__2Efun__28min__2Ebool__2Cmin__2Ebool__29__29, type,
    ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Efun_28min_2Ebool_2Cmin_2Ebool_29_29 : $tType).
thf(sy_2E__24equal, type,
    _24equal : ty_2Enum_2Enum > ty_2Enum_2Enum > ty_2Emin_2Ebool).
thf(sy_2Ec__2Ebool__2ECOND__2Enum__2Enum, type,
    c_2Ebool_2ECOND_2Enum_2Enum : ty_2Emin_2Ebool > ty_2Enum_2Enum > ty_2Enum_2Enum > ty_2Enum_2Enum).
thf(sy_2E__24equal, type,
    _24equal : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 > ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 > ty_2Emin_2Ebool).
thf(sy_2E__24not, type,
    _24not : ty_2Emin_2Ebool > ty_2Emin_2Ebool).
thf(sy_2Ec__2Ebool__2ECOND__2Emin__2Ebool, type,
    c_2Ebool_2ECOND_2Emin_2Ebool : ty_2Emin_2Ebool > ty_2Emin_2Ebool > ty_2Emin_2Ebool > ty_2Emin_2Ebool).
thf(sy_2E__24true, type,
    _24true : ty_2Emin_2Ebool).
thf(sy_2E__24equal, type,
    _24equal : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 > ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 > ty_2Emin_2Ebool).
thf(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28min__2Ebool__2Cmin__2Ebool__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 : ty_2Emin_2Ebool > ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 > ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 > ty_2Emin_2Ebool > ty_2Emin_2Ebool).
thf(sy_2Ec__2Ebool__2ECOND__2Emin__2Efun__28num__2Enum__2Cnum__2Enum__29, type,
    c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 : ty_2Emin_2Ebool > ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 > ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 > ty_2Enum_2Enum > ty_2Enum_2Enum).
thf(sy_2E__24false, type,
    _24false : ty_2Emin_2Ebool).
% Helpers (9)
thf(help_2Eif__True, axiom,
    ((![HX : ty_2Emin_2Ebool]: (![HY : ty_2Emin_2Ebool]: ((c_2Ebool_2ECOND_2Emin_2Ebool @ _24true @ HX @ HY) <=> HX))))).
thf(help_2Eif__True_2E2, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: (_24equal @ (c_2Ebool_2ECOND_2Enum_2Enum @ _24true @ HX @ HY) @ HX))))).
thf(help_2Eif__True_2E3, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (_24equal @ (c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 @ _24true @ HX @ HY) @ HX))))).
thf(help_2Eif__True_2E4, axiom,
    ((![HX : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (![HY : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (_24equal @ (c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ _24true @ HX @ HY) @ HX))))).
thf(help_2Eif__False, axiom,
    ((![HX : ty_2Emin_2Ebool]: (![HY : ty_2Emin_2Ebool]: ((c_2Ebool_2ECOND_2Emin_2Ebool @ _24false @ HX @ HY) <=> HY))))).
thf(help_2Eif__False_2E2, axiom,
    ((![HX : ty_2Enum_2Enum]: (![HY : ty_2Enum_2Enum]: (_24equal @ (c_2Ebool_2ECOND_2Enum_2Enum @ _24false @ HX @ HY) @ HY))))).
thf(help_2Eif__False_2E3, axiom,
    ((![HX : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (![HY : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: (_24equal @ (c_2Ebool_2ECOND_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29 @ _24false @ HX @ HY) @ HY))))).
thf(help_2Eif__False_2E4, axiom,
    ((![HX : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (![HY : ty_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29]: (_24equal @ (c_2Ebool_2ECOND_2Emin_2Efun_28num_2Enum_2Cnum_2Enum_29 @ _24false @ HX @ HY) @ HY))))).
thf(help_2Ebool__cases, axiom,
    ((![HB : ty_2Emin_2Ebool]: ((HB <=> _24true) | (HB <=> _24false))))).
% Facts (0)
% Conjecture (1)
thf(conjecture, conjecture,
    ((![P : ty_2Emin_2Ebool]: (![X : ty_2Enum_2Enum]: (![Y : ty_2Enum_2Enum]: (![V_use__bool : ty_2Emin_2Efun_28min_2Ebool_2Cmin_2Ebool_29]: ((_24equal @ (c_2Ebool_2ECOND_2Enum_2Enum @ P @ X @ Y) @ X) & ((_24equal @ (^[X : ty_2Enum_2Enum]: X) @ (^[X : ty_2Enum_2Enum]: X)) & ((V_use__bool @ (_24not @ P)) & (_24equal @ X @ X)))))))))).
